### ISSUE TITLE
GitHub and Tokens

### ISSUE THREAD

**Issue by df-jablan** [hkhako/OS_Dreamfactory2.0#1]
If you change the `"prefer-dist": true` to `"prefer-source": true` in the DF2's composer.json file, you might not need a GitHub token.  

It really depends on how many packages are pulled from GitHub. 

No promises but worth a try.

**Comment by hkhako** [comment]
Thanks, let me give it a try.

**Comment by hkhako** [comment]
Yes, it seems to work.
