### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by Sakpal** [hkhako/OS_Dreamfactory2.0#2]
Hey,

Thanks for the tutorial.

Everything worked except for the last step of "php artisan dreamfactory:setup". Getting the following error when trying to exceute it.
SQLSTATE[HY000] [2002] No such file or directory

Any idea how to resolve it?

**Comment by hkhako** [comment]
try to SSH to openshift, and run the following commands.  These lines are in the automated scripts, but not executed for some reasons.

cd ${OPENSHIFT_HOMEDIR}/app-root/runtime/repo
sed -i '/DB_DRIVER=/ c\DB_DRIVER=mysql' .env-dist
sed -i '/DB_HOST=/ c\DB_HOST='$OPENSHIFT_MYSQL_DB_HOST'' .env-dist
sed -i '/DB_PORT=/ c\DB_PORT='$OPENSHIFT_MYSQL_DB_PORT'' .env-dist
sed -i '/DB_USERNAME=/ c\DB_USERNAME='$OPENSHIFT_MYSQL_DB_USERNAME'' .env-dist
sed -i '/DB_PASSWORD=/ c\DB_PASSWORD='$OPENSHIFT_MYSQL_DB_PASSWORD'' .env-dist
sed -i '/DB_DATABASE=/ c\DB_DATABASE='$OPENSHIFT_APP_NAME'' .env-dist
cp .env-dist .env

**Comment by Sakpal** [comment]
Hey,

Thank You for the script.

I did it the hard way of finding out the hostname & pasting it in the .env file.
Thanks for the integration. Great Job.

**Comment by hkhako** [comment]
Glad you find it working.  Enjoy dreamfactory 2.0
